# .github/workflows/ci.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout ä»£ç 
      - uses: actions/checkout@v3

      # è®¾ç½® Node.js ç‰ˆæœ¬
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.18.0"

      # å®‰è£…ä¾èµ–
      - name: Install dependencies
        run: npm install

      # æ„å»ºé¡¹ç›®
      - name: Build project
        run: npm run build

      # å‘é€é€šçŸ¥åˆ° Discord å’Œ API
      - name: Send failure notification on error
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          MESSAGE="ğŸš¨ Build failed on branch '${{ github.ref }}'. Please check the logs for details."
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            -d "{\"stage\": \"Build\", \"status\": \"Failure\", \"logs\": \"$MESSAGE\"}" \
            https://itmd-536-group3-project.vercel.app/api/status
        
      - name: Send success notification on error        
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          MESSAGE="âœ… Build succeeded on branch '${{ github.ref }}'."
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"$MESSAGE\"}" $DISCORD_WEBHOOK_URL
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-api-key: $API_KEY" \
            -d "{\"stage\": \"Build\", \"status\": \"Failure\", \"logs\": \"$MESSAGE\"}" \
            https://itmd-536-group3-project.vercel.app/api/status